from .specialties_serializer import SpecialtiesSerializer
from .doctors_serializer import DoctorsSerializer
from .schedules_serializer import SchedulesSerializer
from .diarys_serializer import DiarysSerializer
from .appointments_serializer import AppointmentsSerializer
