from .specialties_view_test_case import SpecialtiesViewTestCase
from .doctors_view_test_case import DoctorsViewTestCase
from .specialties_view_test_case import SpecialtiesViewTestCase
from .appointments_view_test_case import AppointmentsViewTestCase
from .appointments_delete_view_test_case import AppointmentsDeleteViewTestCase